source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'

group :assets do
	gem 'sprockets-rails', '~> 2.0.0'  
	gem 'sass-rails', '~> 4.0.0'
	gem 'coffee-rails', '~> 4.0.0'
	gem 'uglifier', '>= 1.3.0'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.13.2'
end

group :test do
  gem 'capybara', '2.0.2'
end

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

group :doc do
	gem 'sdoc', require: false
end

